### PR TITLE
Add PyJWT to support IBM Certificate Manager

### PR DESCRIPTION
**Pull request by osenbach**
I'd like to use IBM Functions to support all of the various IBM Certificate Manager workflows, such as ordering, renewing, expiring, etc... and to do so I need to decode a JWT encoded payload send in the notification.  Currently, this isn't possible via Python3 actions as a result of the PyJWT module not included as a requirement.

### CODE REVIEW

**Comment by osenbach** [comment]
@dubee or @falkzoll mind a review / merge?

**Comment by osenbach** [comment]
@falkzoll any chance we can add PyJWT so that I can decode IBM Cert Manager messages?

**Comment by falkzoll** [comment]
Sorry did not see this PR at the first time :-(. Let me have a look to see if we can add this.
Would it be ok for you if we would only add it to the latest (python3.7) runtime?

**Comment by osenbach** [comment]
Hey @falkzoll.  Sure!

**Comment by falkzoll** [comment]
Added PyJWT to the python:3.7 runtime with PR https://github.com/ibm-functions/runtime-python/pull/95. Thanks for providing your input 👍 .

The updated version of this runtime is now available in IBM Cloud. Feel free to check it out and get back with more proposals to improve this runtime.
Closing this PR :-).

**Pull request closed without merging**
